# If you change this file, please restart the server process.

# Site settings
title: UNIC
email: association.unic@laposte.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

##
timezone: Europe/Paris

defaults:
  -
    scope:
      path: ""
      type: "posts" 
    values:
      is_post: true
      permalink: /:categories/:title
      layout: "post"

  -
    scope:
      path: "_posts/sorties"
    values:
      category: "sorties"

  -
    scope:
      path: "_posts/activites"
    values:
      category: "activites"

  -
    scope:
      path: "_posts/evenements"
    values:
      category: "evenements"
